name: e3pose
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas
  - pip:
    - fvcore
    - iopath
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - alabaster==0.7.16
    - async-timeout==4.0.3
    - attrs==23.2.0
    - babel==2.16.0
    - batchgenerators==0.25
    - click==8.1.7
    - contourpy==1.1.1
    - cycler==0.12.1
    - Deprecated==1.2.14
    - dicom2nifti==2.4.9
    - docopt==0.6.2
    - docutils==0.19
    - e3nn==0.5.5
    - et_xmlfile==2.0.0
    - exceptiongroup==1.2.2
    - filelock==3.13.1
    - fonttools==4.43.1
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - humanize==4.9.0
    - imageio==2.32.0
    - imagesize==1.4.1
    - iniconfig==2.1.0
    - Jinja2==3.1.2
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - lazy_loader==0.3
    - lightning==2.5.0.post0
    - lightning-utilities==0.10.1
    - linecache2==1.0.0
    - markdown-it-py==3.0.0
    - MarkupSafe==2.1.3
    - matplotlib==3.10.0
    - mdurl==0.1.2
    - MedPy==0.4.0
    - monai==1.4.0
    - mpmath==1.3.0
    - multidict==6.0.4
    - networkx==3.2.1
    - nibabel==5.1.0
    - nnunet==1.7.1
    - nose==1.3.7
    - numpy==1.26.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.1.105
    - opencv-python==4.10.0.84
    - openpyxl==3.1.5
    - opt-einsum==3.3.0
    - opt-einsum-fx==0.1.4
    - packaging==23.2
    - pandas==2.1.4
    - patsy==1.0.1
    - Pillow==10.0.1
    - pluggy==1.5.0
    - pydicom==2.4.3
    - Pygments==2.17.2
    - pykwalify==1.8.0
    - pyparsing==3.1.1
    - pyradiomics==3.0.1
    - pytest==8.3.5
    - python-dateutil==2.8.2
    - python-gdcm==3.0.22
    - pytorch-lightning==2.1.3
    - pytz==2023.3.post1
    - PyWavelets==1.6.0
    - PyYAML==6.0.1
    - rich==13.7.0
    - ruamel.yaml==0.18.6
    - ruamel.yaml.clib==0.2.8
    - scikit-image==0.22.0
    - scikit-learn==1.6.0
    - scipy==1.11.2
    - shellingham==1.5.4
    - SimpleITK==2.3.1
    - six==1.16.0
    - snowballstemmer==2.2.0
    - Sphinx==6.2.1
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - sphstat==1.0.6
    - statsmodels==0.14.4
    - sympy==1.13.1
    - threadpoolctl==3.2.0
    - tifffile==2023.9.26
    - tomli==2.2.1
    - torch==2.2.1
    - torchaudio==2.2.1
    - torchmetrics==1.3.0.post0
    - torchvision==0.17.1
    - torchio==0.20.6
    - traceback2==1.4.0
    - triton==2.2.0
    - typer==0.9.0
    - typing==3.7.4.3
    - typing_extensions==4.12.2
    - unittest2==1.1.0
    - webcolors==24.11.1
    - wrapt==1.16.0
    - yarl==1.9.4
prefix: /path/to/envs/e3pose